# site settings
title: Steve Hoang
subtitle: Live your life you love!
email: hi@stevehoang.com
description: Celebrate life's precious moments through the lens. Explore my collection of cherished memories, where every photograph tells a unique story. Discover the power of remembrance, one snapshot at a time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Steve Hoang
street_address: Le Van Sy
city: Ho Chi Minh City
state: HCMC
zip_code: 72100
country: Vietnam
phone: (+84) 934 479 679

# social settings
500px_url:
facebook_url: https://www.facebook.com/sky.quietly
github_url: https://github.com/lotusk08
gitlab_url: 
googleplus_url:
instagram_url: https://www.instagram.com/whitelotusk09/
linkedin_url: https://www.linkedin.com/in/steve-hoang-a59076a3/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/lotusk08

# build settings
markdown: kramdown

sass:
  style: compressed
